apiVersion: v1
kind: Pod
metadata:
  name: dual
  labels:
    app: master
spec:

  restartPolicy: Never

  containers:

  - name: frontend
    image: gcr.io/sept-248413/market-front:v1
    ports:
    - containerPort: 3000
    

  - name: backend
    image: gcr.io/sept-248413/market-app:v1
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: dualservice
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    targetPort: 8080
    name: front
  - port: 3000
    targetPort: 3000
    name: back
  selector:
    app: master
  type: LoadBalancer