apiVersion: v1
kind: Pod
metadata:
  name: frontendpod
  labels:
    app: master
spec:

  restartPolicy: Never

  containers:

  - name: frontendcon
    image: gcr.io/sept-248413/market-front:v1
    ports:
    - containerPort: 3000
    


---
apiVersion: v1
kind: Service
metadata:
  name: frontendserv
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 3000
    name: front
  selector:
    app: master
  type: LoadBalancer